import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { App as AntdApp, Layout } from 'antd'
import { AuthProvider } from "@/context/AuthContext";
import PageHeader from "@/app/components/header";
import PageFooter from "@/app/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Zippy Send</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AntdApp>
            <Layout style={{ minHeight: '100vh' }}>
              <PageHeader />
              {children}
              <PageFooter />
            </Layout>
          </AntdApp>
        </AuthProvider>

      </body>
    </html>
  );
}
